<?php

namespace Database\Seeders;

use App\Models\Inspection;
use Illuminate\Database\Seeder;

class InspectionSeeder extends Seeder
{
    /**
     * Pemeriksaan kendaraan (handover & return) untuk transaksi yang sudah
     * melalui proses serah terima. Ditulis eksplisit tanpa factory/faker/loop.
     *
     * Aturan yang dijaga:
     *  - Setiap transaksi berstatus rented/completed/cancelled (yang sudah
     *    handover_at bukan null) memiliki satu inspeksi 'handover'.
     *  - Setiap transaksi COMPLETED memiliki satu inspeksi 'return'.
     *  - Odometer return > odometer handover; selisih masuk akal.
     *  - Ditulis eksplisit untuk transaksi terpilih agar file tidak terlalu
     *    panjang; transaksi yang didokumentasikan diwakili secara lengkap.
     *
     * type    : handover | return | routine
     * fuel    : empty | quarter | half | three_quarters | full
     * condition: good | minor | major
     * tire     : good | worn | replace
     * complete : lengkap | kurang
     */
    public function run(): void
    {
        Inspection::insert([

            // ── TRX 1 — handover ──────────────────────────────────────────────
            ['id' => 1, 'vehicle_id' => 1, 'transaction_id' => 1, 'type' => 'handover',
                'inspected_at' => '2025-01-07 08:35:00', 'inspected_by' => 6,
                'odometer' => 82140, 'fuel_level' => 'full',
                'exterior_condition' => 'good', 'interior_condition' => 'good',
                'tire_condition' => 'good', 'completeness' => 'lengkap',
                'missing_items' => null, 'existing_damage' => null, 'new_damage' => null,
                'notes' => null, 'vehicle_status_after' => 'disewa',
                'created_at' => '2025-01-07 08:36:00', 'updated_at' => '2025-01-07 08:36:00'],
            // ── TRX 1 — return ────────────────────────────────────────────────
            ['id' => 2, 'vehicle_id' => 1, 'transaction_id' => 1, 'type' => 'return',
                'inspected_at' => '2025-01-09 09:20:00', 'inspected_by' => 6,
                'odometer' => 82618, 'fuel_level' => 'half',
                'exterior_condition' => 'good', 'interior_condition' => 'good',
                'tire_condition' => 'good', 'completeness' => 'lengkap',
                'missing_items' => null, 'existing_damage' => null, 'new_damage' => null,
                'notes' => 'Kondisi baik, kabin bersih.', 'vehicle_status_after' => 'dibersihkan',
                'created_at' => '2025-01-09 09:22:00', 'updated_at' => '2025-01-09 09:22:00'],

            // ── TRX 2 — handover ──────────────────────────────────────────────
            ['id' => 3, 'vehicle_id' => 4, 'transaction_id' => 2, 'type' => 'handover',
                'inspected_at' => '2025-01-10 09:20:00', 'inspected_by' => 7,
                'odometer' => 148320, 'fuel_level' => 'full',
                'exterior_condition' => 'good', 'interior_condition' => 'good',
                'tire_condition' => 'good', 'completeness' => 'lengkap',
                'missing_items' => null, 'existing_damage' => 'Goresan tipis bumper belakang (lama).', 'new_damage' => null,
                'notes' => null, 'vehicle_status_after' => 'disewa',
                'created_at' => '2025-01-10 09:22:00', 'updated_at' => '2025-01-10 09:22:00'],
            // ── TRX 2 — return ────────────────────────────────────────────────
            ['id' => 4, 'vehicle_id' => 4, 'transaction_id' => 2, 'type' => 'return',
                'inspected_at' => '2025-01-13 08:50:00', 'inspected_by' => 7,
                'odometer' => 148874, 'fuel_level' => 'quarter',
                'exterior_condition' => 'good', 'interior_condition' => 'good',
                'tire_condition' => 'good', 'completeness' => 'lengkap',
                'missing_items' => null, 'existing_damage' => null, 'new_damage' => null,
                'notes' => 'Kendaraan dikembalikan bersih.', 'vehicle_status_after' => 'tersedia',
                'created_at' => '2025-01-13 08:52:00', 'updated_at' => '2025-01-13 08:52:00'],

            // ── TRX 3 — handover ──────────────────────────────────────────────
            ['id' => 5, 'vehicle_id' => 13, 'transaction_id' => 3, 'type' => 'handover',
                'inspected_at' => '2025-01-14 10:15:00', 'inspected_by' => 6,
                'odometer' => 42180, 'fuel_level' => 'full',
                'exterior_condition' => 'good', 'interior_condition' => 'good',
                'tire_condition' => 'good', 'completeness' => 'lengkap',
                'missing_items' => null, 'existing_damage' => null, 'new_damage' => null,
                'notes' => null, 'vehicle_status_after' => 'disewa',
                'created_at' => '2025-01-14 10:17:00', 'updated_at' => '2025-01-14 10:17:00'],
            // ── TRX 3 — return ────────────────────────────────────────────────
            ['id' => 6, 'vehicle_id' => 13, 'transaction_id' => 3, 'type' => 'return',
                'inspected_at' => '2025-01-15 10:30:00', 'inspected_by' => 6,
                'odometer' => 42364, 'fuel_level' => 'three_quarters',
                'exterior_condition' => 'good', 'interior_condition' => 'good',
                'tire_condition' => 'good', 'completeness' => 'lengkap',
                'missing_items' => null, 'existing_damage' => null, 'new_damage' => null,
                'notes' => null, 'vehicle_status_after' => 'tersedia',
                'created_at' => '2025-01-15 10:32:00', 'updated_at' => '2025-01-15 10:32:00'],

            // ── TRX 4 — handover ──────────────────────────────────────────────
            ['id' => 7, 'vehicle_id' => 21, 'transaction_id' => 4, 'type' => 'handover',
                'inspected_at' => '2025-01-19 08:25:00', 'inspected_by' => 7,
                'odometer' => 96710, 'fuel_level' => 'full',
                'exterior_condition' => 'good', 'interior_condition' => 'good',
                'tire_condition' => 'good', 'completeness' => 'lengkap',
                'missing_items' => null, 'existing_damage' => null, 'new_damage' => null,
                'notes' => null, 'vehicle_status_after' => 'disewa',
                'created_at' => '2025-01-19 08:27:00', 'updated_at' => '2025-01-19 08:27:00'],
            // ── TRX 4 — return ────────────────────────────────────────────────
            ['id' => 8, 'vehicle_id' => 21, 'transaction_id' => 4, 'type' => 'return',
                'inspected_at' => '2025-01-22 10:20:00', 'inspected_by' => 7,
                'odometer' => 97183, 'fuel_level' => 'quarter',
                'exterior_condition' => 'good', 'interior_condition' => 'minor',
                'tire_condition' => 'good', 'completeness' => 'lengkap',
                'missing_items' => null, 'existing_damage' => null, 'new_damage' => null,
                'notes' => 'Karpet kotor; perlu dibersihkan.', 'vehicle_status_after' => 'dibersihkan',
                'created_at' => '2025-01-22 10:22:00', 'updated_at' => '2025-01-22 10:22:00'],

            // ── TRX 5 — handover ──────────────────────────────────────────────
            ['id' => 9, 'vehicle_id' => 16, 'transaction_id' => 5, 'type' => 'handover',
                'inspected_at' => '2025-01-24 09:15:00', 'inspected_by' => 6,
                'odometer' => 108340, 'fuel_level' => 'full',
                'exterior_condition' => 'good', 'interior_condition' => 'good',
                'tire_condition' => 'good', 'completeness' => 'lengkap',
                'missing_items' => null, 'existing_damage' => null, 'new_damage' => null,
                'notes' => null, 'vehicle_status_after' => 'disewa',
                'created_at' => '2025-01-24 09:17:00', 'updated_at' => '2025-01-24 09:17:00'],
            // ── TRX 5 — return ────────────────────────────────────────────────
            ['id' => 10, 'vehicle_id' => 16, 'transaction_id' => 5, 'type' => 'return',
                'inspected_at' => '2025-01-27 09:05:00', 'inspected_by' => 6,
                'odometer' => 108817, 'fuel_level' => 'half',
                'exterior_condition' => 'good', 'interior_condition' => 'good',
                'tire_condition' => 'good', 'completeness' => 'lengkap',
                'missing_items' => null, 'existing_damage' => null, 'new_damage' => null,
                'notes' => null, 'vehicle_status_after' => 'tersedia',
                'created_at' => '2025-01-27 09:07:00', 'updated_at' => '2025-01-27 09:07:00'],

            // ── TRX 6 — handover ──────────────────────────────────────────────
            ['id' => 11, 'vehicle_id' => 11, 'transaction_id' => 6, 'type' => 'handover',
                'inspected_at' => '2025-02-03 08:30:00', 'inspected_by' => 7,
                'odometer' => 66240, 'fuel_level' => 'full',
                'exterior_condition' => 'good', 'interior_condition' => 'good',
                'tire_condition' => 'good', 'completeness' => 'lengkap',
                'missing_items' => null, 'existing_damage' => null, 'new_damage' => null,
                'notes' => null, 'vehicle_status_after' => 'disewa',
                'created_at' => '2025-02-03 08:32:00', 'updated_at' => '2025-02-03 08:32:00'],
            // ── TRX 6 — return ────────────────────────────────────────────────
            ['id' => 12, 'vehicle_id' => 11, 'transaction_id' => 6, 'type' => 'return',
                'inspected_at' => '2025-02-05 07:55:00', 'inspected_by' => 7,
                'odometer' => 66587, 'fuel_level' => 'three_quarters',
                'exterior_condition' => 'good', 'interior_condition' => 'good',
                'tire_condition' => 'good', 'completeness' => 'lengkap',
                'missing_items' => null, 'existing_damage' => null, 'new_damage' => null,
                'notes' => null, 'vehicle_status_after' => 'tersedia',
                'created_at' => '2025-02-05 07:57:00', 'updated_at' => '2025-02-05 07:57:00'],

            // ── TRX 7 — handover ──────────────────────────────────────────────
            ['id' => 13, 'vehicle_id' => 5, 'transaction_id' => 7, 'type' => 'handover',
                'inspected_at' => '2025-02-08 09:10:00', 'inspected_by' => 6,
                'odometer' => 30140, 'fuel_level' => 'full',
                'exterior_condition' => 'good', 'interior_condition' => 'good',
                'tire_condition' => 'good', 'completeness' => 'lengkap',
                'missing_items' => null, 'existing_damage' => null, 'new_damage' => null,
                'notes' => null, 'vehicle_status_after' => 'disewa',
                'created_at' => '2025-02-08 09:12:00', 'updated_at' => '2025-02-08 09:12:00'],
            // ── TRX 7 — return ────────────────────────────────────────────────
            ['id' => 14, 'vehicle_id' => 5, 'transaction_id' => 7, 'type' => 'return',
                'inspected_at' => '2025-02-12 11:25:00', 'inspected_by' => 6,
                'odometer' => 30827, 'fuel_level' => 'quarter',
                'exterior_condition' => 'good', 'interior_condition' => 'good',
                'tire_condition' => 'good', 'completeness' => 'lengkap',
                'missing_items' => null, 'existing_damage' => null, 'new_damage' => null,
                'notes' => 'Bahan bakar dikembalikan lebih rendah dari kondisi awal.', 'vehicle_status_after' => 'tersedia',
                'created_at' => '2025-02-12 11:27:00', 'updated_at' => '2025-02-12 11:27:00'],

            // ── TRX 8 — handover ──────────────────────────────────────────────
            ['id' => 15, 'vehicle_id' => 4, 'transaction_id' => 8, 'type' => 'handover',
                'inspected_at' => '2025-02-15 08:20:00', 'inspected_by' => 7,
                'odometer' => 149380, 'fuel_level' => 'full',
                'exterior_condition' => 'good', 'interior_condition' => 'good',
                'tire_condition' => 'good', 'completeness' => 'lengkap',
                'missing_items' => null, 'existing_damage' => 'Goresan tipis bumper belakang (lama).', 'new_damage' => null,
                'notes' => null, 'vehicle_status_after' => 'disewa',
                'created_at' => '2025-02-15 08:22:00', 'updated_at' => '2025-02-15 08:22:00'],
            // ── TRX 8 — return ────────────────────────────────────────────────
            ['id' => 16, 'vehicle_id' => 4, 'transaction_id' => 8, 'type' => 'return',
                'inspected_at' => '2025-02-18 08:10:00', 'inspected_by' => 7,
                'odometer' => 150162, 'fuel_level' => 'half',
                'exterior_condition' => 'good', 'interior_condition' => 'good',
                'tire_condition' => 'good', 'completeness' => 'lengkap',
                'missing_items' => null, 'existing_damage' => null, 'new_damage' => null,
                'notes' => null, 'vehicle_status_after' => 'tersedia',
                'created_at' => '2025-02-18 08:12:00', 'updated_at' => '2025-02-18 08:12:00'],

            // ── TRX 9 — handover ──────────────────────────────────────────────
            ['id' => 17, 'vehicle_id' => 6, 'transaction_id' => 9, 'type' => 'handover',
                'inspected_at' => '2025-02-22 10:20:00', 'inspected_by' => 6,
                'odometer' => 74160, 'fuel_level' => 'full',
                'exterior_condition' => 'good', 'interior_condition' => 'good',
                'tire_condition' => 'good', 'completeness' => 'lengkap',
                'missing_items' => null, 'existing_damage' => null, 'new_damage' => null,
                'notes' => null, 'vehicle_status_after' => 'disewa',
                'created_at' => '2025-02-22 10:22:00', 'updated_at' => '2025-02-22 10:22:00'],
            // ── TRX 9 — return ────────────────────────────────────────────────
            ['id' => 18, 'vehicle_id' => 6, 'transaction_id' => 9, 'type' => 'return',
                'inspected_at' => '2025-02-23 09:45:00', 'inspected_by' => 6,
                'odometer' => 74318, 'fuel_level' => 'three_quarters',
                'exterior_condition' => 'good', 'interior_condition' => 'good',
                'tire_condition' => 'good', 'completeness' => 'lengkap',
                'missing_items' => null, 'existing_damage' => null, 'new_damage' => null,
                'notes' => null, 'vehicle_status_after' => 'tersedia',
                'created_at' => '2025-02-23 09:47:00', 'updated_at' => '2025-02-23 09:47:00'],

            // ── TRX 10 — handover ─────────────────────────────────────────────
            ['id' => 19, 'vehicle_id' => 22, 'transaction_id' => 10, 'type' => 'handover',
                'inspected_at' => '2025-02-26 09:15:00', 'inspected_by' => 7,
                'odometer' => 54780, 'fuel_level' => 'full',
                'exterior_condition' => 'good', 'interior_condition' => 'good',
                'tire_condition' => 'good', 'completeness' => 'lengkap',
                'missing_items' => null, 'existing_damage' => null, 'new_damage' => null,
                'notes' => null, 'vehicle_status_after' => 'disewa',
                'created_at' => '2025-02-26 09:17:00', 'updated_at' => '2025-02-26 09:17:00'],
            // ── TRX 10 — return ───────────────────────────────────────────────
            ['id' => 20, 'vehicle_id' => 22, 'transaction_id' => 10, 'type' => 'return',
                'inspected_at' => '2025-02-28 09:00:00', 'inspected_by' => 7,
                'odometer' => 55218, 'fuel_level' => 'half',
                'exterior_condition' => 'good', 'interior_condition' => 'good',
                'tire_condition' => 'good', 'completeness' => 'lengkap',
                'missing_items' => null, 'existing_damage' => null, 'new_damage' => null,
                'notes' => null, 'vehicle_status_after' => 'tersedia',
                'created_at' => '2025-02-28 09:02:00', 'updated_at' => '2025-02-28 09:02:00'],

            // ── TRX 20 — Innova Reborn Lebaran — handover ──────────────────────
            ['id' => 21, 'vehicle_id' => 4, 'transaction_id' => 20, 'type' => 'handover',
                'inspected_at' => '2025-05-03 08:25:00', 'inspected_by' => 7,
                'odometer' => 155840, 'fuel_level' => 'full',
                'exterior_condition' => 'good', 'interior_condition' => 'good',
                'tire_condition' => 'good', 'completeness' => 'lengkap',
                'missing_items' => null, 'existing_damage' => 'Goresan tipis bumper belakang (lama).', 'new_damage' => null,
                'notes' => 'Perjalanan jauh — cek ban sebelum berangkat.', 'vehicle_status_after' => 'disewa',
                'created_at' => '2025-05-03 08:27:00', 'updated_at' => '2025-05-03 08:27:00'],
            ['id' => 22, 'vehicle_id' => 4, 'transaction_id' => 20, 'type' => 'return',
                'inspected_at' => '2025-05-08 08:10:00', 'inspected_by' => 7,
                'odometer' => 157283, 'fuel_level' => 'quarter',
                'exterior_condition' => 'good', 'interior_condition' => 'minor',
                'tire_condition' => 'good', 'completeness' => 'lengkap',
                'missing_items' => null, 'existing_damage' => null, 'new_damage' => null,
                'notes' => 'Kabin kotor (remah makanan). Perlu pembersihan interior.', 'vehicle_status_after' => 'dibersihkan',
                'created_at' => '2025-05-08 08:12:00', 'updated_at' => '2025-05-08 08:12:00'],

            // ── TRX 29 — Terios sewa mingguan — handover ──────────────────────
            ['id' => 23, 'vehicle_id' => 12, 'transaction_id' => 29, 'type' => 'handover',
                'inspected_at' => '2025-06-28 08:30:00', 'inspected_by' => 6,
                'odometer' => 120480, 'fuel_level' => 'full',
                'exterior_condition' => 'good', 'interior_condition' => 'good',
                'tire_condition' => 'good', 'completeness' => 'lengkap',
                'missing_items' => null, 'existing_damage' => null, 'new_damage' => null,
                'notes' => null, 'vehicle_status_after' => 'disewa',
                'created_at' => '2025-06-28 08:32:00', 'updated_at' => '2025-06-28 08:32:00'],
            ['id' => 24, 'vehicle_id' => 12, 'transaction_id' => 29, 'type' => 'return',
                'inspected_at' => '2025-07-05 08:00:00', 'inspected_by' => 6,
                'odometer' => 121394, 'fuel_level' => 'half',
                'exterior_condition' => 'minor', 'interior_condition' => 'good',
                'tire_condition' => 'worn', 'completeness' => 'lengkap',
                'missing_items' => null, 'existing_damage' => null, 'new_damage' => 'Lecet kecil pada pintu kiri belakang.',
                'notes' => 'Ban mulai aus di bagian depan. Perlu perhatian segera.', 'vehicle_status_after' => 'tersedia',
                'created_at' => '2025-07-05 08:02:00', 'updated_at' => '2025-07-05 08:02:00'],

            // ── TRX 34 — Terios sewa mingguan kedua — handover ────────────────
            ['id' => 25, 'vehicle_id' => 12, 'transaction_id' => 34, 'type' => 'handover',
                'inspected_at' => '2025-07-30 08:15:00', 'inspected_by' => 7,
                'odometer' => 121394, 'fuel_level' => 'full',
                'exterior_condition' => 'minor', 'interior_condition' => 'good',
                'tire_condition' => 'worn', 'completeness' => 'lengkap',
                'missing_items' => null, 'existing_damage' => 'Lecet kecil pintu kiri belakang; ban depan mulai aus.', 'new_damage' => null,
                'notes' => 'Kondisi ban dicatat; perlu ganti setelah kembali.', 'vehicle_status_after' => 'disewa',
                'created_at' => '2025-07-30 08:17:00', 'updated_at' => '2025-07-30 08:17:00'],
            ['id' => 26, 'vehicle_id' => 12, 'transaction_id' => 34, 'type' => 'return',
                'inspected_at' => '2025-08-06 08:00:00', 'inspected_by' => 7,
                'odometer' => 122428, 'fuel_level' => 'quarter',
                'exterior_condition' => 'minor', 'interior_condition' => 'good',
                'tire_condition' => 'worn', 'completeness' => 'lengkap',
                'missing_items' => null, 'existing_damage' => null, 'new_damage' => null,
                'notes' => 'Ban depan perlu segera diganti.', 'vehicle_status_after' => 'tersedia',
                'created_at' => '2025-08-06 08:02:00', 'updated_at' => '2025-08-06 08:02:00'],

            // ── TRX 37 — Innova Reborn wisata Ijen — handover ─────────────────
            ['id' => 27, 'vehicle_id' => 4, 'transaction_id' => 37, 'type' => 'handover',
                'inspected_at' => '2025-08-15 08:15:00', 'inspected_by' => 6,
                'odometer' => 160740, 'fuel_level' => 'full',
                'exterior_condition' => 'good', 'interior_condition' => 'good',
                'tire_condition' => 'good', 'completeness' => 'lengkap',
                'missing_items' => null, 'existing_damage' => 'Goresan bumper belakang.', 'new_damage' => null,
                'notes' => null, 'vehicle_status_after' => 'disewa',
                'created_at' => '2025-08-15 08:17:00', 'updated_at' => '2025-08-15 08:17:00'],
            ['id' => 28, 'vehicle_id' => 4, 'transaction_id' => 37, 'type' => 'return',
                'inspected_at' => '2025-08-18 10:30:00', 'inspected_by' => 6,
                'odometer' => 162184, 'fuel_level' => 'quarter',
                'exterior_condition' => 'good', 'interior_condition' => 'good',
                'tire_condition' => 'good', 'completeness' => 'lengkap',
                'missing_items' => null, 'existing_damage' => null, 'new_damage' => null,
                'notes' => null, 'vehicle_status_after' => 'tersedia',
                'created_at' => '2025-08-18 10:32:00', 'updated_at' => '2025-08-18 10:32:00'],

            // ── TRX 46 — Terios sewa mingguan Oktober — handover ──────────────
            ['id' => 29, 'vehicle_id' => 12, 'transaction_id' => 46, 'type' => 'handover',
                'inspected_at' => '2025-10-09 08:20:00', 'inspected_by' => 6,
                'odometer' => 122428, 'fuel_level' => 'full',
                'exterior_condition' => 'minor', 'interior_condition' => 'good',
                'tire_condition' => 'good', 'completeness' => 'lengkap',
                'missing_items' => null, 'existing_damage' => 'Lecet kecil pintu kiri belakang (sudah dipoles sebagian).', 'new_damage' => null,
                'notes' => 'Ban sudah diganti baru.', 'vehicle_status_after' => 'disewa',
                'created_at' => '2025-10-09 08:22:00', 'updated_at' => '2025-10-09 08:22:00'],
            ['id' => 30, 'vehicle_id' => 12, 'transaction_id' => 46, 'type' => 'return',
                'inspected_at' => '2025-10-16 08:10:00', 'inspected_by' => 6,
                'odometer' => 123540, 'fuel_level' => 'half',
                'exterior_condition' => 'minor', 'interior_condition' => 'good',
                'tire_condition' => 'good', 'completeness' => 'lengkap',
                'missing_items' => null, 'existing_damage' => null, 'new_damage' => null,
                'notes' => null, 'vehicle_status_after' => 'tersedia',
                'created_at' => '2025-10-16 08:12:00', 'updated_at' => '2025-10-16 08:12:00'],

            // ── TRX 47 — Innova Zenix 7 hari Oktober — handover ───────────────
            ['id' => 31, 'vehicle_id' => 5, 'transaction_id' => 47, 'type' => 'handover',
                'inspected_at' => '2025-10-16 09:15:00', 'inspected_by' => 7,
                'odometer' => 55630, 'fuel_level' => 'full',
                'exterior_condition' => 'good', 'interior_condition' => 'good',
                'tire_condition' => 'good', 'completeness' => 'lengkap',
                'missing_items' => null, 'existing_damage' => null, 'new_damage' => null,
                'notes' => 'Perjalanan jauh ke Jogja.', 'vehicle_status_after' => 'disewa',
                'created_at' => '2025-10-16 09:17:00', 'updated_at' => '2025-10-16 09:17:00'],
            ['id' => 32, 'vehicle_id' => 5, 'transaction_id' => 47, 'type' => 'return',
                'inspected_at' => '2025-10-23 09:00:00', 'inspected_by' => 7,
                'odometer' => 57084, 'fuel_level' => 'quarter',
                'exterior_condition' => 'good', 'interior_condition' => 'good',
                'tire_condition' => 'good', 'completeness' => 'lengkap',
                'missing_items' => null, 'existing_damage' => null, 'new_damage' => null,
                'notes' => null, 'vehicle_status_after' => 'tersedia',
                'created_at' => '2025-10-23 09:02:00', 'updated_at' => '2025-10-23 09:02:00'],

            // ── TRX 55 — Innova Zenix 7 hari Desember — handover ──────────────
            ['id' => 33, 'vehicle_id' => 5, 'transaction_id' => 55, 'type' => 'handover',
                'inspected_at' => '2025-12-18 08:30:00', 'inspected_by' => 7,
                'odometer' => 71940, 'fuel_level' => 'full',
                'exterior_condition' => 'good', 'interior_condition' => 'good',
                'tire_condition' => 'good', 'completeness' => 'lengkap',
                'missing_items' => null, 'existing_damage' => null, 'new_damage' => null,
                'notes' => 'Wisata akhir tahun ke Lombok.', 'vehicle_status_after' => 'disewa',
                'created_at' => '2025-12-18 08:32:00', 'updated_at' => '2025-12-18 08:32:00'],
            ['id' => 34, 'vehicle_id' => 5, 'transaction_id' => 55, 'type' => 'return',
                'inspected_at' => '2025-12-25 10:20:00', 'inspected_by' => 7,
                'odometer' => 73218, 'fuel_level' => 'quarter',
                'exterior_condition' => 'good', 'interior_condition' => 'minor',
                'tire_condition' => 'good', 'completeness' => 'lengkap',
                'missing_items' => null, 'existing_damage' => null, 'new_damage' => null,
                'notes' => 'Kabin sedikit berdebu; perlu dibersihkan.', 'vehicle_status_after' => 'dibersihkan',
                'created_at' => '2025-12-25 10:22:00', 'updated_at' => '2025-12-25 10:22:00'],

            // ── TRX 60 — Innova Reborn pernikahan Situbondo — handover ─────────
            ['id' => 35, 'vehicle_id' => 4, 'transaction_id' => 60, 'type' => 'handover',
                'inspected_at' => '2026-01-22 09:20:00', 'inspected_by' => 6,
                'odometer' => 174020, 'fuel_level' => 'full',
                'exterior_condition' => 'good', 'interior_condition' => 'good',
                'tire_condition' => 'good', 'completeness' => 'lengkap',
                'missing_items' => null, 'existing_damage' => 'Goresan bumper belakang (lama).', 'new_damage' => null,
                'notes' => null, 'vehicle_status_after' => 'disewa',
                'created_at' => '2026-01-22 09:22:00', 'updated_at' => '2026-01-22 09:22:00'],
            ['id' => 36, 'vehicle_id' => 4, 'transaction_id' => 60, 'type' => 'return',
                'inspected_at' => '2026-01-25 09:10:00', 'inspected_by' => 6,
                'odometer' => 174658, 'fuel_level' => 'half',
                'exterior_condition' => 'good', 'interior_condition' => 'good',
                'tire_condition' => 'good', 'completeness' => 'lengkap',
                'missing_items' => null, 'existing_damage' => null, 'new_damage' => null,
                'notes' => null, 'vehicle_status_after' => 'tersedia',
                'created_at' => '2026-01-25 09:12:00', 'updated_at' => '2026-01-25 09:12:00'],

            // ── TRX 64 — Innova Zenix proyek Malang — handover ────────────────
            ['id' => 37, 'vehicle_id' => 5, 'transaction_id' => 64, 'type' => 'handover',
                'inspected_at' => '2026-02-18 08:25:00', 'inspected_by' => 6,
                'odometer' => 78140, 'fuel_level' => 'full',
                'exterior_condition' => 'good', 'interior_condition' => 'good',
                'tire_condition' => 'good', 'completeness' => 'lengkap',
                'missing_items' => null, 'existing_damage' => null, 'new_damage' => null,
                'notes' => null, 'vehicle_status_after' => 'disewa',
                'created_at' => '2026-02-18 08:27:00', 'updated_at' => '2026-02-18 08:27:00'],
            ['id' => 38, 'vehicle_id' => 5, 'transaction_id' => 64, 'type' => 'return',
                'inspected_at' => '2026-02-21 10:30:00', 'inspected_by' => 6,
                'odometer' => 78924, 'fuel_level' => 'quarter',
                'exterior_condition' => 'good', 'interior_condition' => 'good',
                'tire_condition' => 'good', 'completeness' => 'lengkap',
                'missing_items' => null, 'existing_damage' => null, 'new_damage' => null,
                'notes' => null, 'vehicle_status_after' => 'tersedia',
                'created_at' => '2026-02-21 10:32:00', 'updated_at' => '2026-02-21 10:32:00'],

            // ── TRX 75 — Innova Zenix wisata Bromo 4 hari — handover ──────────
            ['id' => 39, 'vehicle_id' => 5, 'transaction_id' => 75, 'type' => 'handover',
                'inspected_at' => '2026-05-12 08:20:00', 'inspected_by' => 7,
                'odometer' => 83680, 'fuel_level' => 'full',
                'exterior_condition' => 'good', 'interior_condition' => 'good',
                'tire_condition' => 'good', 'completeness' => 'lengkap',
                'missing_items' => null, 'existing_damage' => null, 'new_damage' => null,
                'notes' => 'Wisata panjang Bromo–Ijen–Pantai.', 'vehicle_status_after' => 'disewa',
                'created_at' => '2026-05-12 08:22:00', 'updated_at' => '2026-05-12 08:22:00'],
            ['id' => 40, 'vehicle_id' => 5, 'transaction_id' => 75, 'type' => 'return',
                'inspected_at' => '2026-05-16 09:30:00', 'inspected_by' => 7,
                'odometer' => 84927, 'fuel_level' => 'quarter',
                'exterior_condition' => 'good', 'interior_condition' => 'minor',
                'tire_condition' => 'good', 'completeness' => 'lengkap',
                'missing_items' => null, 'existing_damage' => null, 'new_damage' => null,
                'notes' => 'Beberapa noda lumpur di bumper — perlu cuci eksterior.', 'vehicle_status_after' => 'dibersihkan',
                'created_at' => '2026-05-16 09:32:00', 'updated_at' => '2026-05-16 09:32:00'],

            // ── TRX 81 — Terios sewa mingguan Juni — handover ─────────────────
            ['id' => 41, 'vehicle_id' => 12, 'transaction_id' => 81, 'type' => 'handover',
                'inspected_at' => '2026-06-25 08:10:00', 'inspected_by' => 6,
                'odometer' => 158240, 'fuel_level' => 'full',
                'exterior_condition' => 'good', 'interior_condition' => 'good',
                'tire_condition' => 'good', 'completeness' => 'lengkap',
                'missing_items' => null, 'existing_damage' => 'Lecet kecil pintu kiri belakang (sudah dipoles).', 'new_damage' => null,
                'notes' => null, 'vehicle_status_after' => 'disewa',
                'created_at' => '2026-06-25 08:12:00', 'updated_at' => '2026-06-25 08:12:00'],
            ['id' => 42, 'vehicle_id' => 12, 'transaction_id' => 81, 'type' => 'return',
                'inspected_at' => '2026-07-02 08:05:00', 'inspected_by' => 6,
                'odometer' => 159483, 'fuel_level' => 'quarter',
                'exterior_condition' => 'good', 'interior_condition' => 'good',
                'tire_condition' => 'good', 'completeness' => 'lengkap',
                'missing_items' => null, 'existing_damage' => null, 'new_damage' => null,
                'notes' => null, 'vehicle_status_after' => 'tersedia',
                'created_at' => '2026-07-02 08:07:00', 'updated_at' => '2026-07-02 08:07:00'],

            // ── TRX 83 — Innova Zenix VIP Surabaya — handover ────────────────
            ['id' => 43, 'vehicle_id' => 24, 'transaction_id' => 83, 'type' => 'handover',
                'inspected_at' => '2026-07-14 08:15:00', 'inspected_by' => 7,
                'odometer' => 42180, 'fuel_level' => 'full',
                'exterior_condition' => 'good', 'interior_condition' => 'good',
                'tire_condition' => 'good', 'completeness' => 'lengkap',
                'missing_items' => null, 'existing_damage' => null, 'new_damage' => null,
                'notes' => 'Unit premium; tamu VIP.', 'vehicle_status_after' => 'disewa',
                'created_at' => '2026-07-14 08:17:00', 'updated_at' => '2026-07-14 08:17:00'],
            ['id' => 44, 'vehicle_id' => 24, 'transaction_id' => 83, 'type' => 'return',
                'inspected_at' => '2026-07-17 08:05:00', 'inspected_by' => 7,
                'odometer' => 43086, 'fuel_level' => 'half',
                'exterior_condition' => 'good', 'interior_condition' => 'good',
                'tire_condition' => 'good', 'completeness' => 'lengkap',
                'missing_items' => null, 'existing_damage' => null, 'new_damage' => null,
                'notes' => 'Kendaraan dikembalikan dalam kondisi prima.', 'vehicle_status_after' => 'tersedia',
                'created_at' => '2026-07-17 08:07:00', 'updated_at' => '2026-07-17 08:07:00'],

            // ── TRX 91 — XL7 sewa 3 hari September — handover ────────────────
            ['id' => 45, 'vehicle_id' => 22, 'transaction_id' => 91, 'type' => 'handover',
                'inspected_at' => '2026-09-08 08:20:00', 'inspected_by' => 7,
                'odometer' => 119640, 'fuel_level' => 'full',
                'exterior_condition' => 'good', 'interior_condition' => 'good',
                'tire_condition' => 'good', 'completeness' => 'lengkap',
                'missing_items' => null, 'existing_damage' => null, 'new_damage' => null,
                'notes' => null, 'vehicle_status_after' => 'disewa',
                'created_at' => '2026-09-08 08:22:00', 'updated_at' => '2026-09-08 08:22:00'],
            ['id' => 46, 'vehicle_id' => 22, 'transaction_id' => 91, 'type' => 'return',
                'inspected_at' => '2026-09-11 10:30:00', 'inspected_by' => 7,
                'odometer' => 120192, 'fuel_level' => 'quarter',
                'exterior_condition' => 'good', 'interior_condition' => 'good',
                'tire_condition' => 'good', 'completeness' => 'lengkap',
                'missing_items' => null, 'existing_damage' => null, 'new_damage' => null,
                'notes' => null, 'vehicle_status_after' => 'tersedia',
                'created_at' => '2026-09-11 10:32:00', 'updated_at' => '2026-09-11 10:32:00'],

            // ── TRX 95 — Ayla 4 hari, terlambat besar — handover ─────────────
            ['id' => 47, 'vehicle_id' => 14, 'transaction_id' => 95, 'type' => 'handover',
                'inspected_at' => '2026-09-24 09:15:00', 'inspected_by' => 7,
                'odometer' => 44820, 'fuel_level' => 'full',
                'exterior_condition' => 'good', 'interior_condition' => 'good',
                'tire_condition' => 'good', 'completeness' => 'lengkap',
                'missing_items' => null, 'existing_damage' => null, 'new_damage' => null,
                'notes' => null, 'vehicle_status_after' => 'disewa',
                'created_at' => '2026-09-24 09:17:00', 'updated_at' => '2026-09-24 09:17:00'],
            ['id' => 48, 'vehicle_id' => 14, 'transaction_id' => 95, 'type' => 'return',
                'inspected_at' => '2026-09-28 16:10:00', 'inspected_by' => 7,
                'odometer' => 45614, 'fuel_level' => 'quarter',
                'exterior_condition' => 'good', 'interior_condition' => 'good',
                'tire_condition' => 'good', 'completeness' => 'lengkap',
                'missing_items' => null, 'existing_damage' => null, 'new_damage' => null,
                'notes' => 'Terlambat 7 jam. Denda sudah dibayar.', 'vehicle_status_after' => 'dibersihkan',
                'created_at' => '2026-09-28 16:12:00', 'updated_at' => '2026-09-28 16:12:00'],

            // ── TRX 96 — Avanza 1.5 G 3 hari, terlambat besar — handover ─────
            ['id' => 49, 'vehicle_id' => 25, 'transaction_id' => 96, 'type' => 'handover',
                'inspected_at' => '2026-09-25 08:20:00', 'inspected_by' => 6,
                'odometer' => 56840, 'fuel_level' => 'full',
                'exterior_condition' => 'good', 'interior_condition' => 'good',
                'tire_condition' => 'good', 'completeness' => 'lengkap',
                'missing_items' => null, 'existing_damage' => null, 'new_damage' => null,
                'notes' => null, 'vehicle_status_after' => 'disewa',
                'created_at' => '2026-09-25 08:22:00', 'updated_at' => '2026-09-25 08:22:00'],
            ['id' => 50, 'vehicle_id' => 25, 'transaction_id' => 96, 'type' => 'return',
                'inspected_at' => '2026-09-28 17:10:00', 'inspected_by' => 6,
                'odometer' => 57849, 'fuel_level' => 'quarter',
                'exterior_condition' => 'good', 'interior_condition' => 'minor',
                'tire_condition' => 'good', 'completeness' => 'lengkap',
                'missing_items' => null, 'existing_damage' => null, 'new_damage' => null,
                'notes' => 'Karpet kotor dan kursi bau — perlu dibersihkan. Terlambat 9 jam, denda sudah dibayar.', 'vehicle_status_after' => 'dibersihkan',
                'created_at' => '2026-09-28 17:12:00', 'updated_at' => '2026-09-28 17:12:00'],

            // ── TRX 97 — Avanza hitam aktif — handover saja ───────────────────
            ['id' => 51, 'vehicle_id' => 2, 'transaction_id' => 97, 'type' => 'handover',
                'inspected_at' => '2026-09-27 09:20:00', 'inspected_by' => 6,
                'odometer' => 117682, 'fuel_level' => 'full',
                'exterior_condition' => 'good', 'interior_condition' => 'good',
                'tire_condition' => 'good', 'completeness' => 'lengkap',
                'missing_items' => null, 'existing_damage' => null, 'new_damage' => null,
                'notes' => null, 'vehicle_status_after' => 'disewa',
                'created_at' => '2026-09-27 09:22:00', 'updated_at' => '2026-09-27 09:22:00'],

            // ── TRX 98 — Innova Zenix G aktif — handover saja ─────────────────
            ['id' => 52, 'vehicle_id' => 5, 'transaction_id' => 98, 'type' => 'handover',
                'inspected_at' => '2026-09-28 08:30:00', 'inspected_by' => 7,
                'odometer' => 87482, 'fuel_level' => 'full',
                'exterior_condition' => 'good', 'interior_condition' => 'good',
                'tire_condition' => 'good', 'completeness' => 'lengkap',
                'missing_items' => null, 'existing_damage' => null, 'new_damage' => null,
                'notes' => null, 'vehicle_status_after' => 'disewa',
                'created_at' => '2026-09-28 08:32:00', 'updated_at' => '2026-09-28 08:32:00'],

            // ── TRX 99 — Raize aktif — handover saja ──────────────────────────
            ['id' => 53, 'vehicle_id' => 8, 'transaction_id' => 99, 'type' => 'handover',
                'inspected_at' => '2026-09-27 10:15:00', 'inspected_by' => 6,
                'odometer' => 70624, 'fuel_level' => 'full',
                'exterior_condition' => 'good', 'interior_condition' => 'good',
                'tire_condition' => 'good', 'completeness' => 'lengkap',
                'missing_items' => null, 'existing_damage' => null, 'new_damage' => null,
                'notes' => null, 'vehicle_status_after' => 'disewa',
                'created_at' => '2026-09-27 10:17:00', 'updated_at' => '2026-09-27 10:17:00'],

            // ── TRX 100 — Terios aktif — handover saja ───────────────────────
            ['id' => 54, 'vehicle_id' => 12, 'transaction_id' => 100, 'type' => 'handover',
                'inspected_at' => '2026-09-26 08:20:00', 'inspected_by' => 7,
                'odometer' => 171684, 'fuel_level' => 'full',
                'exterior_condition' => 'good', 'interior_condition' => 'good',
                'tire_condition' => 'good', 'completeness' => 'lengkap',
                'missing_items' => null, 'existing_damage' => 'Lecet pintu kiri belakang (lama, sudah dipoles).', 'new_damage' => null,
                'notes' => null, 'vehicle_status_after' => 'disewa',
                'created_at' => '2026-09-26 08:22:00', 'updated_at' => '2026-09-26 08:22:00'],

            // ── TRX 101 — BR-V aktif — handover saja ────────────────────────
            ['id' => 55, 'vehicle_id' => 17, 'transaction_id' => 101, 'type' => 'handover',
                'inspected_at' => '2026-09-26 09:10:00', 'inspected_by' => 6,
                'odometer' => 120984, 'fuel_level' => 'full',
                'exterior_condition' => 'good', 'interior_condition' => 'good',
                'tire_condition' => 'good', 'completeness' => 'lengkap',
                'missing_items' => null, 'existing_damage' => null, 'new_damage' => null,
                'notes' => null, 'vehicle_status_after' => 'disewa',
                'created_at' => '2026-09-26 09:12:00', 'updated_at' => '2026-09-26 09:12:00'],

            // ── TRX 102 — Ertiga aktif — handover saja ──────────────────────
            ['id' => 56, 'vehicle_id' => 21, 'transaction_id' => 102, 'type' => 'handover',
                'inspected_at' => '2026-09-25 08:15:00', 'inspected_by' => 7,
                'odometer' => 157480, 'fuel_level' => 'full',
                'exterior_condition' => 'good', 'interior_condition' => 'good',
                'tire_condition' => 'good', 'completeness' => 'lengkap',
                'missing_items' => null, 'existing_damage' => null, 'new_damage' => null,
                'notes' => null, 'vehicle_status_after' => 'disewa',
                'created_at' => '2026-09-25 08:17:00', 'updated_at' => '2026-09-25 08:17:00'],

            // ── TRX 103 — Mobilio RS aktif — handover saja ──────────────────
            ['id' => 57, 'vehicle_id' => 27, 'transaction_id' => 103, 'type' => 'handover',
                'inspected_at' => '2026-09-27 09:15:00', 'inspected_by' => 6,
                'odometer' => 48584, 'fuel_level' => 'full',
                'exterior_condition' => 'good', 'interior_condition' => 'good',
                'tire_condition' => 'good', 'completeness' => 'lengkap',
                'missing_items' => null, 'existing_damage' => null, 'new_damage' => null,
                'notes' => null, 'vehicle_status_after' => 'disewa',
                'created_at' => '2026-09-27 09:17:00', 'updated_at' => '2026-09-27 09:17:00'],

        ]);
    }
}
